[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro-error = "1.0.4"
darling = "0.21.2"
proc-macro2 = "1.0.103"
strum = { version = "0.27.2", features = ["derive"] }
Inflector = "0.11.4"
